server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never

spring:
  application:
    name: SpringBootIntro
  datasource:
    url: jdbc:postgresql://localhost:5432/sbootintro
    username: dev_user
    password: dev_user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      '[hibernate.format_sql]': true


logging:
  file:
    name: log/studentapp.log
    parent:
      # Date - Level - Thread - Which logger object - Message itself
      file: "%d %d-5level [%thread] %logger:%msg%n"
    level:
      '[org.springframework.web]': WARN
      '[org.hibernate]': INFO
      '[com.tpe]': INFO

management:
  endpoints:
    web:
      exposure:
        include: ['health', 'loggers', 'env', 'beans']


#spring.application.name=SpringBootIntro

#server.port=8081
#server.error.include-binding-errors=always
#server.error.include-message=always
#server.error.include-stacktrace=never
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/sbootintro
#spring.datasource.username=dev_user
#spring.datasource.password=dev_user

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
#spring.jpa.properties.hibernate.format_sql=true